from _typeshed import Incomplete
from checker.geometry import Aabb

EPS: float

def box(lo, hi) -> Aabb: ...

UNIT: Incomplete

def test_relation_codes(other, expected) -> None: ...
def test_inverse_codes() -> None: ...
def test_inside_is_not_within() -> None: ...
def test_tolerance_decides_contact_versus_gap() -> None: ...
