from _typeshed import Incomplete

HDR_2D: Incomplete

def widget(name, extent, position): ...
def build(entities, claims): ...
def test_above_is_plus_y_in_2d() -> None: ...
def test_thin_containment_survives_tolerance_in_2d() -> None: ...
def test_planar_overlap_still_caught_in_2d() -> None: ...
def test_3d_above_is_still_plus_z() -> None: ...
