def only(scene): ...
def test_distance_is_point_to_region(make_scene) -> None: ...
def test_distance_can_fail(make_scene) -> None: ...
def test_ordinal_quantity_in_a_metric_predicate_is_a_type_error(make_scene) -> None: ...
def test_grid_units_need_a_declared_cell_size(make_scene) -> None: ...
def test_faces_requires_a_front(make_scene) -> None: ...
def test_chair_faces_the_desk(make_scene) -> None: ...
def test_alignment_is_tolerance_bound(make_scene) -> None: ...
def test_chair_is_antiparallel_to_the_desk_hence_parallel(make_scene) -> None: ...
