def verdicts(scene): ...
def test_world_anchor_needs_no_frame(make_scene) -> None: ...
def test_locale_anchor_reads_the_grounds_own_front(make_scene) -> None: ...
def test_locale_on_a_frontless_ground_is_an_error(make_scene) -> None: ...
def test_projective_term_without_any_frame_is_an_error(make_scene) -> None: ...
def test_group_anchor_uses_the_viewers_left(make_scene) -> None: ...
def test_a_lamp_on_the_desk_is_not_left_of_it(make_scene) -> None: ...
def test_group_anchor_without_a_viewpoint_is_an_error(make_scene) -> None: ...
