from _typeshed import Incomplete

def only(scene): ...

NO_TWO_OVERLAP: Incomplete

def test_no_two_objects_overlap(make_scene) -> None: ...
def test_an_overlap_is_caught_with_its_witness(make_scene) -> None: ...
def test_count_stops_the_delete_everything_strategy(make_scene) -> None: ...
def test_every_binds_the_figure_over_a_set(make_scene) -> None: ...
