def document_without(key: str) -> dict: ...
def test_a_missing_tolerance_does_not_parse() -> None: ...
def test_a_missing_frame_does_not_parse() -> None: ...
def test_a_non_canonical_frame_is_rejected_at_the_door() -> None: ...
def test_the_type_ontology_is_user_extensible(make_scene) -> None: ...
def test_free_dofs_are_reported_not_scored(make_scene) -> None: ...
