from _typeshed import Incomplete

EXAMPLES: Incomplete
PLAIN_SVG: str

def test_emitter_output_round_trips_to_the_same_positions() -> None: ...
def test_plain_svg_uses_the_metre_contract_with_y_flip() -> None: ...
def test_prose_and_fences_around_the_svg_are_tolerated() -> None: ...
def test_a_completion_with_no_svg_is_a_value_error() -> None: ...
