from _typeshed import Incomplete

ROLLING_BALL: Incomplete
DESK: Incomplete

def scene_with(claims, timebase: str = 'seconds', make_scene=None): ...
def test_pose_is_interpolated_at_the_stated_instant(make_scene) -> None: ...
def test_the_same_claim_fails_later(make_scene) -> None: ...
def test_hold_is_a_sampled_invariant(make_scene) -> None: ...
def test_hold_reports_where_it_broke(make_scene) -> None: ...
def test_hold_on_an_ordinal_timebase_is_a_type_error(make_scene) -> None: ...
def test_allen_orders_events(make_scene) -> None: ...
