from checker import CheckReport as CheckReport

FRAME_NOTE: str
SVG_NOTE: str

def build_task_prompt(task: dict) -> str: ...
def build_svg_task_prompt(task: dict) -> str: ...
def build_blind_retry() -> str: ...
def build_feedback(report: CheckReport) -> str: ...
def extract_poses(text: str) -> dict: ...
