from .geometry import point_to_region_distance as point_to_region_distance
from .scene import Scene as Scene
from .units import Quantity as Quantity

OPS: dict[str, str]

class PredicateError(Exception): ...

def distance(scene: Scene, figure: str, ground: str, t: float = 0.0) -> float: ...
def distance_holds(scene: Scene, figure: str, ground: str, op: str, quantity: Quantity, t: float = 0.0) -> tuple[bool, str]: ...
def compare(measured: float, op: str, threshold: float, eps: float) -> bool: ...
def faces(scene: Scene, subject: str, target: str, t: float = 0.0) -> tuple[bool, str]: ...
def axis_angle_holds(scene: Scene, a: str, b: str, expected_deg: float, t: float = 0.0) -> tuple[bool, str]: ...
def aligned(scene: Scene, a: str, b: str, axis: str = 'x', t: float = 0.0) -> tuple[bool, str]: ...
