Vec3 = tuple[float, float, float]
Quat = tuple[float, float, float, float]
IDENTITY: Quat
ZERO: Vec3
UP: Vec3
FORWARD: Vec3
RIGHT: Vec3

def add(a: Vec3, b: Vec3) -> Vec3: ...
def sub(a: Vec3, b: Vec3) -> Vec3: ...
def scaled(a: Vec3, k: float) -> Vec3: ...
def dot(a: Vec3, b: Vec3) -> float: ...
def cross(a: Vec3, b: Vec3) -> Vec3: ...
def length(a: Vec3) -> float: ...
def normalize(a: Vec3) -> Vec3: ...
def lerp(a: Vec3, b: Vec3, u: float) -> Vec3: ...
def quat_normalize(q: Quat) -> Quat: ...
def rotate(q: Quat, v: Vec3) -> Vec3: ...
def basis_of(q: Quat) -> tuple[Vec3, Vec3, Vec3]: ...
def angle_between(a: Vec3, b: Vec3) -> float: ...
