from .vecmath import Quat as Quat, Vec3 as Vec3
from dataclasses import dataclass

Interval = tuple[float, float]

@dataclass(frozen=True)
class Aabb:
    lo: Vec3
    hi: Vec3
    def centre(self) -> Vec3: ...
    def half_extent(self) -> Vec3: ...

def box_region(position: Vec3, orientation: Quat, extent: Vec3) -> Aabb: ...
def sphere_region(position: Vec3, radius: float) -> Aabb: ...
def point_region(position: Vec3) -> Aabb: ...
def interval_along(region: Aabb, axis: Vec3) -> Interval: ...
def point_to_region_distance(point: Vec3, region: Aabb) -> float: ...
