from dataclasses import dataclass

METRIC: dict[str, float]
DEVICE: dict[str, float]
GRID: set[str]
NORMALIZED: set[str]
ORDINAL: set[str]
ANGLE: dict[str, float]
TIME: dict[str, float]

class UnitTypeError(Exception): ...

@dataclass(frozen=True)
class UnitContext:
    dpi: float | None = ...
    cell_size_m: float | None = ...
    parent_extent_m: float | None = ...

def kind_of(unit: str) -> str: ...

@dataclass(frozen=True)
class Quantity:
    value: float
    unit: str
    def kind(self) -> str: ...
    def to_metres(self, ctx: UnitContext) -> float: ...

def parse(text: str) -> tuple[float, str]: ...
def parse_quantity(text: str) -> Quantity: ...
def angle_to_radians(value: float, unit: str) -> float: ...
def time_to_seconds(value: float, unit: str) -> float: ...
